"""vprism错误代码和消息标准化."""

from enum import Enum


class ErrorCode(str, Enum):
    """标准化的错误代码枚举."""

    # 通用错误
    GENERAL_ERROR = "GENERAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"

    # 提供商相关错误
    PROVIDER_ERROR = "PROVIDER_ERROR"
    PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"

    # 认证和授权错误
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR"
    API_KEY_INVALID = "API_KEY_INVALID"
    API_KEY_EXPIRED = "API_KEY_EXPIRED"

    # 速率限制错误
    RATE_LIMIT_ERROR = "RATE_LIMIT_ERROR"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"

    # 数据相关错误
    DATA_NOT_FOUND = "DATA_NOT_FOUND"
    DATA_VALIDATION_ERROR = "DATA_VALIDATION_ERROR"
    DATA_FORMAT_ERROR = "DATA_FORMAT_ERROR"
    DATA_INCOMPLETE = "DATA_INCOMPLETE"

    # 缓存相关错误
    CACHE_ERROR = "CACHE_ERROR"
    CACHE_MISS = "CACHE_MISS"
    CACHE_CONNECTION_ERROR = "CACHE_CONNECTION_ERROR"

    # 网络相关错误
    NETWORK_ERROR = "NETWORK_ERROR"
    CONNECTION_TIMEOUT = "CONNECTION_TIMEOUT"
    CONNECTION_REFUSED = "CONNECTION_REFUSED"
    DNS_RESOLUTION_ERROR = "DNS_RESOLUTION_ERROR"

    # 查询相关错误
    QUERY_ERROR = "QUERY_ERROR"
    INVALID_QUERY = "INVALID_QUERY"
    UNSUPPORTED_PARAMETERS = "UNSUPPORTED_PARAMETERS"
    NO_CAPABLE_PROVIDER = "NO_CAPABLE_PROVIDER"

    # 存储相关错误
    STORAGE_ERROR = "STORAGE_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"

    # 系统内部错误
    INTERNAL_ERROR = "INTERNAL_ERROR"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
