version: '3.8'

services:
  vprism-api:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - VPRISM_ENV=development
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - vprism_data:/app/data
    depends_on:
      - redis
      - duckdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  vprism-worker:
    build:
      context: .
      target: development
    environment:
      - VPRISM_ENV=development
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - vprism_data:/app/data
    depends_on:
      - redis
      - duckdb
    command: ["uv", "run", "python", "-m", "vprism.cli.worker"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  duckdb:
    image: duckdb/duckdb:latest
    volumes:
      - vprism_data:/data
    environment:
      - DUCKDB_DATABASE=/data/vprism.duckdb

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  vprism_data:
  redis_data:
  prometheus_data:
  grafana_data: