"""Shared constants for the VPrism CLI."""

VALIDATION_EXIT_CODE = 10
PROVIDER_EXIT_CODE = 20
DATA_QUALITY_EXIT_CODE = 30
RECONCILE_EXIT_CODE = 40
SYSTEM_EXIT_CODE = 50

__all__ = [
    "VALIDATION_EXIT_CODE",
    "PROVIDER_EXIT_CODE",
    "DATA_QUALITY_EXIT_CODE",
    "RECONCILE_EXIT_CODE",
    "SYSTEM_EXIT_CODE",
]
